import Foundation
import XCTest
@testable import DBDeckCore

/// Round-trip real contra um Postgres local. Desligado por padrão porque precisa de
/// servidor; ligue com:
///
///     DBDECK_PG_HOST=localhost DBDECK_PG_USER=postgres swift test --filter PostgresIntegration
///
/// Cobre o que só aparece com um servidor de verdade: decodificação por posição,
/// tipos do `information_schema`, DDL vindo do `pg_catalog`, contadores de sequence
/// e de IDENTITY, índices, constraints e views.
final class PostgresIntegrationTests: XCTestCase {
    private var host: String? { ProcessInfo.processInfo.environment["DBDECK_PG_HOST"] }
    private var user: String { ProcessInfo.processInfo.environment["DBDECK_PG_USER"] ?? "postgres" }
    private var password: String { ProcessInfo.processInfo.environment["DBDECK_PG_PASSWORD"] ?? "" }
    private var port: Int { Int(ProcessInfo.processInfo.environment["DBDECK_PG_PORT"] ?? "") ?? 5432 }

    private func driver(_ database: String) -> PostgresDriver {
        PostgresDriver(config: ConnectionConfig(
            engine: .postgres, host: host ?? "localhost", port: port,
            username: user, password: password, database: database
        ))
    }

    private let source = "dbdeck_it_src"
    private let target = "dbdeck_it_dst"

    func testRoundTripCompleto() async throws {
        try XCTSkipIf(host == nil, "defina DBDECK_PG_HOST para rodar o teste de integração")

        let admin = driver("postgres")
        try await admin.connect()
        for database in [source, target] {
            _ = try? await admin.execute("DROP DATABASE IF EXISTS \(database)")
            try await admin.createDatabase(named: database, charset: nil)
        }
        await admin.disconnect()

        let origin = driver(source)
        try await origin.connect()
        _ = try await origin.execute("""
            CREATE TABLE pais (
              id serial PRIMARY KEY,
              nome varchar(50) NOT NULL UNIQUE,
              populacao numeric(12,2),
              criado_em timestamp DEFAULT now(),
              ativo boolean DEFAULT true,
              meta jsonb
            )
            """)
        _ = try await origin.execute("""
            CREATE TABLE cidade (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              nome varchar(80) NOT NULL,
              pais_id integer NOT NULL REFERENCES pais(id) ON DELETE CASCADE,
              habitantes integer CHECK (habitantes >= 0)
            )
            """)
        _ = try await origin.execute("CREATE INDEX idx_cidade_nome ON cidade(nome)")
        _ = try await origin.execute(
            "CREATE VIEW v_resumo AS SELECT p.nome AS pais, count(c.id) AS cidades FROM pais p LEFT JOIN cidade c ON c.pais_id = p.id GROUP BY p.nome"
        )
        _ = try await origin.execute("""
            INSERT INTO pais (nome, populacao, meta) VALUES
              ('Brasil', 203080756.00, '{"regiao":"América do Sul"}'), ('Portugal', 10467366.00, NULL)
            """)
        _ = try await origin.execute("""
            INSERT INTO cidade (nome, pais_id, habitantes) VALUES
              ('São Paulo', 1, 11451245), ('Lisboa', 2, 545923), ('Caminho C:\\ Barra', 2, 1)
            """)

        // Metadados: a leitura por nome devolvia a mesma célula em colunas homônimas,
        // e os domínios do information_schema chegavam como blob.
        let tables = try await origin.tables()
        XCTAssertEqual(tables.map(\.name).sorted(), ["cidade", "pais", "v_resumo"])
        let columns = try await origin.columns(table: "pais")
        XCTAssertEqual(columns.map(\.name), ["id", "nome", "populacao", "criado_em", "ativo", "meta"])

        let dump = try await SQLDump.dump(driver: origin)
        // O tamanho declarado das colunas precisa sobreviver (information_schema.data_type
        // devolvia "character varying", sem o (50)).
        XCTAssertTrue(dump.contains("character varying(50)"), dump)
        XCTAssertTrue(dump.contains("numeric(12,2)"))
        XCTAssertTrue(dump.contains("GENERATED BY DEFAULT AS IDENTITY"))
        XCTAssertTrue(dump.contains("CREATE INDEX idx_cidade_nome"))
        XCTAssertTrue(dump.contains("FOREIGN KEY"))
        XCTAssertTrue(dump.contains("CHECK"))
        XCTAssertTrue(dump.contains("UNIQUE"))
        XCTAssertTrue(dump.contains("CREATE VIEW"))
        // Barra invertida é literal no Postgres: dobrá-la corromperia o dado.
        XCTAssertTrue(dump.contains(#"'Caminho C:\ Barra'"#))
        // O pool de conexões torna um BEGIN/COMMIT no arquivo pior que inútil.
        XCTAssertFalse(dump.contains("BEGIN;"))
        await origin.disconnect()

        let destination = driver(target)
        try await destination.connect()
        let (statements, errors) = try await SQLDump.importSQL(dump, driver: destination)
        XCTAssertTrue(errors.isEmpty, errors.joined(separator: "\n"))
        XCTAssertGreaterThan(statements, 5)

        let cidades = try await destination.query("SELECT nome FROM cidade ORDER BY id")
        XCTAssertEqual(cidades.rows.map { $0[0].display }, ["São Paulo", "Lisboa", #"Caminho C:\ Barra"#])

        let populacao = try await destination.query("SELECT populacao::text FROM pais WHERE id = 1")
        XCTAssertEqual(populacao.rows.first?.first?.display, "203080756.00")

        // Contadores: serial e IDENTITY precisam continuar de onde a origem parou.
        let proximoPais = try await destination.query("INSERT INTO pais (nome) VALUES ('Chile') RETURNING id")
        XCTAssertEqual(proximoPais.rows.first?.first, .int(3))
        let proximaCidade = try await destination.query("INSERT INTO cidade (nome, pais_id) VALUES ('Porto', 2) RETURNING id")
        XCTAssertEqual(proximaCidade.rows.first?.first, .int(4))

        let resumo = try await destination.query("SELECT count(*) FROM v_resumo")
        XCTAssertEqual(resumo.rows.first?.first, .int(3))
        await destination.disconnect()

        let cleanup = driver("postgres")
        try await cleanup.connect()
        _ = try? await cleanup.execute("DROP DATABASE IF EXISTS \(source)")
        _ = try? await cleanup.execute("DROP DATABASE IF EXISTS \(target)")
        await cleanup.disconnect()
    }
}
